# Generated by Django 3.2.5 on 2021-08-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_project', models.CharField(max_length=50)),
                ('description_project', models.TextField()),
                ('date_created_project', models.DateTimeField(auto_now_add=True)),
                ('creator_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_todo', models.CharField(max_length=50)),
                ('description_todo', models.TextField()),
                ('date_created_todo', models.DateTimeField(auto_now_add=True)),
                ('state_todo', models.CharField(choices=[('Planning', 'Planning state'), ('Running', 'Running state'), ('Finished', 'Finnished state')], default='Planning', max_length=20)),
                ('creator_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
