# Generated by Django 3.2.5 on 2021-08-17 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210817_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=140),
        ),
    ]
