# Generated by Django 3.2.5 on 2021-08-17 18:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin',
            field=models.CharField(default=accounts.models.CustomUser, max_length=140),
        ),
    ]
