# Generated by Django 3.2.5 on 2021-08-17 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_auto_20210817_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin',
            field=models.ManyToManyField(related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
